# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QSizePolicy,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(940, 510)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.keyboardGroup = QGroupBox(self.centralwidget)
        self.keyboardGroup.setObjectName(u"keyboardGroup")
        self.keyboardGroup.setGeometry(QRect(8, 8, 926, 276))
        self.key_esc = QPushButton(self.keyboardGroup)
        self.key_esc.setObjectName(u"key_esc")
        self.key_esc.setGeometry(QRect(10, 20, 36, 36))
        self.key_f1 = QPushButton(self.keyboardGroup)
        self.key_f1.setObjectName(u"key_f1")
        self.key_f1.setGeometry(QRect(80, 20, 36, 36))
        self.key_f2 = QPushButton(self.keyboardGroup)
        self.key_f2.setObjectName(u"key_f2")
        self.key_f2.setGeometry(QRect(120, 20, 36, 36))
        self.key_f3 = QPushButton(self.keyboardGroup)
        self.key_f3.setObjectName(u"key_f3")
        self.key_f3.setGeometry(QRect(160, 20, 36, 36))
        self.key_f4 = QPushButton(self.keyboardGroup)
        self.key_f4.setObjectName(u"key_f4")
        self.key_f4.setGeometry(QRect(200, 20, 36, 36))
        self.key_f5 = QPushButton(self.keyboardGroup)
        self.key_f5.setObjectName(u"key_f5")
        self.key_f5.setGeometry(QRect(260, 20, 36, 36))
        self.key_f6 = QPushButton(self.keyboardGroup)
        self.key_f6.setObjectName(u"key_f6")
        self.key_f6.setGeometry(QRect(300, 20, 36, 36))
        self.key_f7 = QPushButton(self.keyboardGroup)
        self.key_f7.setObjectName(u"key_f7")
        self.key_f7.setGeometry(QRect(340, 20, 36, 36))
        self.key_f8 = QPushButton(self.keyboardGroup)
        self.key_f8.setObjectName(u"key_f8")
        self.key_f8.setGeometry(QRect(380, 20, 36, 36))
        self.key_f9 = QPushButton(self.keyboardGroup)
        self.key_f9.setObjectName(u"key_f9")
        self.key_f9.setGeometry(QRect(440, 20, 36, 36))
        self.key_f10 = QPushButton(self.keyboardGroup)
        self.key_f10.setObjectName(u"key_f10")
        self.key_f10.setGeometry(QRect(480, 20, 36, 36))
        self.key_f11 = QPushButton(self.keyboardGroup)
        self.key_f11.setObjectName(u"key_f11")
        self.key_f11.setGeometry(QRect(520, 20, 36, 36))
        self.key_f12 = QPushButton(self.keyboardGroup)
        self.key_f12.setObjectName(u"key_f12")
        self.key_f12.setGeometry(QRect(560, 20, 36, 36))
        self.key_grave = QPushButton(self.keyboardGroup)
        self.key_grave.setObjectName(u"key_grave")
        self.key_grave.setGeometry(QRect(10, 70, 36, 36))
        self.key_1 = QPushButton(self.keyboardGroup)
        self.key_1.setObjectName(u"key_1")
        self.key_1.setGeometry(QRect(50, 70, 36, 36))
        self.key_2 = QPushButton(self.keyboardGroup)
        self.key_2.setObjectName(u"key_2")
        self.key_2.setGeometry(QRect(90, 70, 36, 36))
        self.key_3 = QPushButton(self.keyboardGroup)
        self.key_3.setObjectName(u"key_3")
        self.key_3.setGeometry(QRect(130, 70, 36, 36))
        self.key_4 = QPushButton(self.keyboardGroup)
        self.key_4.setObjectName(u"key_4")
        self.key_4.setGeometry(QRect(170, 70, 36, 36))
        self.key_5 = QPushButton(self.keyboardGroup)
        self.key_5.setObjectName(u"key_5")
        self.key_5.setGeometry(QRect(210, 70, 36, 36))
        self.key_6 = QPushButton(self.keyboardGroup)
        self.key_6.setObjectName(u"key_6")
        self.key_6.setGeometry(QRect(250, 70, 36, 36))
        self.key_7 = QPushButton(self.keyboardGroup)
        self.key_7.setObjectName(u"key_7")
        self.key_7.setGeometry(QRect(290, 70, 36, 36))
        self.key_8 = QPushButton(self.keyboardGroup)
        self.key_8.setObjectName(u"key_8")
        self.key_8.setGeometry(QRect(330, 70, 36, 36))
        self.key_9 = QPushButton(self.keyboardGroup)
        self.key_9.setObjectName(u"key_9")
        self.key_9.setGeometry(QRect(370, 70, 36, 36))
        self.key_0 = QPushButton(self.keyboardGroup)
        self.key_0.setObjectName(u"key_0")
        self.key_0.setGeometry(QRect(410, 70, 36, 36))
        self.key_minus = QPushButton(self.keyboardGroup)
        self.key_minus.setObjectName(u"key_minus")
        self.key_minus.setGeometry(QRect(450, 70, 36, 36))
        self.key_equals = QPushButton(self.keyboardGroup)
        self.key_equals.setObjectName(u"key_equals")
        self.key_equals.setGeometry(QRect(490, 70, 36, 36))
        self.key_backspace = QPushButton(self.keyboardGroup)
        self.key_backspace.setObjectName(u"key_backspace")
        self.key_backspace.setGeometry(QRect(530, 70, 66, 36))
        self.key_tab = QPushButton(self.keyboardGroup)
        self.key_tab.setObjectName(u"key_tab")
        self.key_tab.setGeometry(QRect(10, 110, 56, 36))
        self.key_q = QPushButton(self.keyboardGroup)
        self.key_q.setObjectName(u"key_q")
        self.key_q.setGeometry(QRect(70, 110, 36, 36))
        self.key_w = QPushButton(self.keyboardGroup)
        self.key_w.setObjectName(u"key_w")
        self.key_w.setGeometry(QRect(110, 110, 36, 36))
        self.key_e = QPushButton(self.keyboardGroup)
        self.key_e.setObjectName(u"key_e")
        self.key_e.setGeometry(QRect(150, 110, 36, 36))
        self.key_r = QPushButton(self.keyboardGroup)
        self.key_r.setObjectName(u"key_r")
        self.key_r.setGeometry(QRect(190, 110, 36, 36))
        self.key_t = QPushButton(self.keyboardGroup)
        self.key_t.setObjectName(u"key_t")
        self.key_t.setGeometry(QRect(230, 110, 36, 36))
        self.key_y = QPushButton(self.keyboardGroup)
        self.key_y.setObjectName(u"key_y")
        self.key_y.setGeometry(QRect(270, 110, 36, 36))
        self.key_u = QPushButton(self.keyboardGroup)
        self.key_u.setObjectName(u"key_u")
        self.key_u.setGeometry(QRect(310, 110, 36, 36))
        self.key_i = QPushButton(self.keyboardGroup)
        self.key_i.setObjectName(u"key_i")
        self.key_i.setGeometry(QRect(350, 110, 36, 36))
        self.key_o = QPushButton(self.keyboardGroup)
        self.key_o.setObjectName(u"key_o")
        self.key_o.setGeometry(QRect(390, 110, 36, 36))
        self.key_p = QPushButton(self.keyboardGroup)
        self.key_p.setObjectName(u"key_p")
        self.key_p.setGeometry(QRect(430, 110, 36, 36))
        self.key_leftbracket = QPushButton(self.keyboardGroup)
        self.key_leftbracket.setObjectName(u"key_leftbracket")
        self.key_leftbracket.setGeometry(QRect(470, 110, 36, 36))
        self.key_rightbracket = QPushButton(self.keyboardGroup)
        self.key_rightbracket.setObjectName(u"key_rightbracket")
        self.key_rightbracket.setGeometry(QRect(510, 110, 36, 36))
        self.key_backslash = QPushButton(self.keyboardGroup)
        self.key_backslash.setObjectName(u"key_backslash")
        self.key_backslash.setGeometry(QRect(550, 110, 46, 36))
        self.key_capslock = QPushButton(self.keyboardGroup)
        self.key_capslock.setObjectName(u"key_capslock")
        self.key_capslock.setGeometry(QRect(10, 150, 66, 36))
        self.key_a = QPushButton(self.keyboardGroup)
        self.key_a.setObjectName(u"key_a")
        self.key_a.setGeometry(QRect(80, 150, 36, 36))
        self.key_s = QPushButton(self.keyboardGroup)
        self.key_s.setObjectName(u"key_s")
        self.key_s.setGeometry(QRect(120, 150, 36, 36))
        self.key_d = QPushButton(self.keyboardGroup)
        self.key_d.setObjectName(u"key_d")
        self.key_d.setGeometry(QRect(160, 150, 36, 36))
        self.key_f = QPushButton(self.keyboardGroup)
        self.key_f.setObjectName(u"key_f")
        self.key_f.setGeometry(QRect(200, 150, 36, 36))
        self.key_g = QPushButton(self.keyboardGroup)
        self.key_g.setObjectName(u"key_g")
        self.key_g.setGeometry(QRect(240, 150, 36, 36))
        self.key_h = QPushButton(self.keyboardGroup)
        self.key_h.setObjectName(u"key_h")
        self.key_h.setGeometry(QRect(280, 150, 36, 36))
        self.key_j = QPushButton(self.keyboardGroup)
        self.key_j.setObjectName(u"key_j")
        self.key_j.setGeometry(QRect(320, 150, 36, 36))
        self.key_k = QPushButton(self.keyboardGroup)
        self.key_k.setObjectName(u"key_k")
        self.key_k.setGeometry(QRect(360, 150, 36, 36))
        self.key_l = QPushButton(self.keyboardGroup)
        self.key_l.setObjectName(u"key_l")
        self.key_l.setGeometry(QRect(400, 150, 36, 36))
        self.key_semicolon = QPushButton(self.keyboardGroup)
        self.key_semicolon.setObjectName(u"key_semicolon")
        self.key_semicolon.setGeometry(QRect(440, 150, 36, 36))
        self.key_quote = QPushButton(self.keyboardGroup)
        self.key_quote.setObjectName(u"key_quote")
        self.key_quote.setGeometry(QRect(480, 150, 36, 36))
        self.key_enter = QPushButton(self.keyboardGroup)
        self.key_enter.setObjectName(u"key_enter")
        self.key_enter.setGeometry(QRect(520, 150, 76, 36))
        self.key_lshift = QPushButton(self.keyboardGroup)
        self.key_lshift.setObjectName(u"key_lshift")
        self.key_lshift.setGeometry(QRect(10, 190, 86, 36))
        self.key_z = QPushButton(self.keyboardGroup)
        self.key_z.setObjectName(u"key_z")
        self.key_z.setGeometry(QRect(100, 190, 36, 36))
        self.key_x = QPushButton(self.keyboardGroup)
        self.key_x.setObjectName(u"key_x")
        self.key_x.setGeometry(QRect(140, 190, 36, 36))
        self.key_c = QPushButton(self.keyboardGroup)
        self.key_c.setObjectName(u"key_c")
        self.key_c.setGeometry(QRect(180, 190, 36, 36))
        self.key_v = QPushButton(self.keyboardGroup)
        self.key_v.setObjectName(u"key_v")
        self.key_v.setGeometry(QRect(220, 190, 36, 36))
        self.key_b = QPushButton(self.keyboardGroup)
        self.key_b.setObjectName(u"key_b")
        self.key_b.setGeometry(QRect(260, 190, 36, 36))
        self.key_n = QPushButton(self.keyboardGroup)
        self.key_n.setObjectName(u"key_n")
        self.key_n.setGeometry(QRect(300, 190, 36, 36))
        self.key_m = QPushButton(self.keyboardGroup)
        self.key_m.setObjectName(u"key_m")
        self.key_m.setGeometry(QRect(340, 190, 36, 36))
        self.key_comma = QPushButton(self.keyboardGroup)
        self.key_comma.setObjectName(u"key_comma")
        self.key_comma.setGeometry(QRect(380, 190, 36, 36))
        self.key_period = QPushButton(self.keyboardGroup)
        self.key_period.setObjectName(u"key_period")
        self.key_period.setGeometry(QRect(420, 190, 36, 36))
        self.key_slash = QPushButton(self.keyboardGroup)
        self.key_slash.setObjectName(u"key_slash")
        self.key_slash.setGeometry(QRect(460, 190, 36, 36))
        self.key_rshift = QPushButton(self.keyboardGroup)
        self.key_rshift.setObjectName(u"key_rshift")
        self.key_rshift.setGeometry(QRect(500, 190, 96, 36))
        self.key_lctrl = QPushButton(self.keyboardGroup)
        self.key_lctrl.setObjectName(u"key_lctrl")
        self.key_lctrl.setGeometry(QRect(10, 230, 56, 36))
        self.key_lwin = QPushButton(self.keyboardGroup)
        self.key_lwin.setObjectName(u"key_lwin")
        self.key_lwin.setGeometry(QRect(70, 230, 46, 36))
        self.key_lalt = QPushButton(self.keyboardGroup)
        self.key_lalt.setObjectName(u"key_lalt")
        self.key_lalt.setGeometry(QRect(120, 230, 46, 36))
        self.key_space = QPushButton(self.keyboardGroup)
        self.key_space.setObjectName(u"key_space")
        self.key_space.setGeometry(QRect(170, 230, 216, 36))
        self.key_ralt = QPushButton(self.keyboardGroup)
        self.key_ralt.setObjectName(u"key_ralt")
        self.key_ralt.setGeometry(QRect(390, 230, 46, 36))
        self.key_rwin = QPushButton(self.keyboardGroup)
        self.key_rwin.setObjectName(u"key_rwin")
        self.key_rwin.setGeometry(QRect(440, 230, 46, 36))
        self.key_menu = QPushButton(self.keyboardGroup)
        self.key_menu.setObjectName(u"key_menu")
        self.key_menu.setGeometry(QRect(490, 230, 46, 36))
        self.key_rctrl = QPushButton(self.keyboardGroup)
        self.key_rctrl.setObjectName(u"key_rctrl")
        self.key_rctrl.setGeometry(QRect(540, 230, 56, 36))
        self.key_printscreen = QPushButton(self.keyboardGroup)
        self.key_printscreen.setObjectName(u"key_printscreen")
        self.key_printscreen.setGeometry(QRect(620, 20, 36, 36))
        font = QFont()
        font.setPointSize(8)
        self.key_printscreen.setFont(font)
        self.key_scrolllock = QPushButton(self.keyboardGroup)
        self.key_scrolllock.setObjectName(u"key_scrolllock")
        self.key_scrolllock.setGeometry(QRect(660, 20, 36, 36))
        self.key_scrolllock.setFont(font)
        self.key_pause = QPushButton(self.keyboardGroup)
        self.key_pause.setObjectName(u"key_pause")
        self.key_pause.setGeometry(QRect(700, 20, 36, 36))
        font1 = QFont()
        font1.setPointSize(7)
        self.key_pause.setFont(font1)
        self.key_insert = QPushButton(self.keyboardGroup)
        self.key_insert.setObjectName(u"key_insert")
        self.key_insert.setGeometry(QRect(620, 70, 36, 36))
        self.key_insert.setFont(font)
        self.key_home = QPushButton(self.keyboardGroup)
        self.key_home.setObjectName(u"key_home")
        self.key_home.setGeometry(QRect(660, 70, 36, 36))
        self.key_home.setFont(font)
        self.key_pageup = QPushButton(self.keyboardGroup)
        self.key_pageup.setObjectName(u"key_pageup")
        self.key_pageup.setGeometry(QRect(700, 70, 36, 36))
        self.key_pageup.setFont(font)
        self.key_delete = QPushButton(self.keyboardGroup)
        self.key_delete.setObjectName(u"key_delete")
        self.key_delete.setGeometry(QRect(620, 110, 36, 36))
        self.key_end = QPushButton(self.keyboardGroup)
        self.key_end.setObjectName(u"key_end")
        self.key_end.setGeometry(QRect(660, 110, 36, 36))
        self.key_end.setFont(font)
        self.key_pagedown = QPushButton(self.keyboardGroup)
        self.key_pagedown.setObjectName(u"key_pagedown")
        self.key_pagedown.setGeometry(QRect(700, 110, 36, 36))
        self.key_pagedown.setFont(font)
        self.key_up = QPushButton(self.keyboardGroup)
        self.key_up.setObjectName(u"key_up")
        self.key_up.setGeometry(QRect(660, 184, 36, 36))
        self.key_left = QPushButton(self.keyboardGroup)
        self.key_left.setObjectName(u"key_left")
        self.key_left.setGeometry(QRect(620, 230, 36, 36))
        self.key_down = QPushButton(self.keyboardGroup)
        self.key_down.setObjectName(u"key_down")
        self.key_down.setGeometry(QRect(660, 230, 36, 36))
        self.key_right = QPushButton(self.keyboardGroup)
        self.key_right.setObjectName(u"key_right")
        self.key_right.setGeometry(QRect(700, 230, 36, 36))
        self.key_numlock = QPushButton(self.keyboardGroup)
        self.key_numlock.setObjectName(u"key_numlock")
        self.key_numlock.setGeometry(QRect(760, 70, 36, 36))
        self.key_numlock.setFont(font)
        self.key_kp_divide = QPushButton(self.keyboardGroup)
        self.key_kp_divide.setObjectName(u"key_kp_divide")
        self.key_kp_divide.setGeometry(QRect(800, 70, 36, 36))
        self.key_kp_multiply = QPushButton(self.keyboardGroup)
        self.key_kp_multiply.setObjectName(u"key_kp_multiply")
        self.key_kp_multiply.setGeometry(QRect(840, 70, 36, 36))
        self.key_kp_subtract = QPushButton(self.keyboardGroup)
        self.key_kp_subtract.setObjectName(u"key_kp_subtract")
        self.key_kp_subtract.setGeometry(QRect(880, 70, 36, 36))
        self.key_kp_7 = QPushButton(self.keyboardGroup)
        self.key_kp_7.setObjectName(u"key_kp_7")
        self.key_kp_7.setGeometry(QRect(760, 110, 36, 36))
        self.key_kp_8 = QPushButton(self.keyboardGroup)
        self.key_kp_8.setObjectName(u"key_kp_8")
        self.key_kp_8.setGeometry(QRect(800, 110, 36, 36))
        self.key_kp_9 = QPushButton(self.keyboardGroup)
        self.key_kp_9.setObjectName(u"key_kp_9")
        self.key_kp_9.setGeometry(QRect(840, 110, 36, 36))
        self.key_kp_add = QPushButton(self.keyboardGroup)
        self.key_kp_add.setObjectName(u"key_kp_add")
        self.key_kp_add.setGeometry(QRect(880, 110, 36, 76))
        self.key_kp_4 = QPushButton(self.keyboardGroup)
        self.key_kp_4.setObjectName(u"key_kp_4")
        self.key_kp_4.setGeometry(QRect(760, 150, 36, 36))
        self.key_kp_5 = QPushButton(self.keyboardGroup)
        self.key_kp_5.setObjectName(u"key_kp_5")
        self.key_kp_5.setGeometry(QRect(800, 150, 36, 36))
        self.key_kp_6 = QPushButton(self.keyboardGroup)
        self.key_kp_6.setObjectName(u"key_kp_6")
        self.key_kp_6.setGeometry(QRect(840, 150, 36, 36))
        self.key_kp_1 = QPushButton(self.keyboardGroup)
        self.key_kp_1.setObjectName(u"key_kp_1")
        self.key_kp_1.setGeometry(QRect(760, 190, 36, 36))
        self.key_kp_2 = QPushButton(self.keyboardGroup)
        self.key_kp_2.setObjectName(u"key_kp_2")
        self.key_kp_2.setGeometry(QRect(800, 190, 36, 36))
        self.key_kp_3 = QPushButton(self.keyboardGroup)
        self.key_kp_3.setObjectName(u"key_kp_3")
        self.key_kp_3.setGeometry(QRect(840, 190, 36, 36))
        self.key_kp_enter = QPushButton(self.keyboardGroup)
        self.key_kp_enter.setObjectName(u"key_kp_enter")
        self.key_kp_enter.setGeometry(QRect(880, 190, 36, 76))
        self.key_kp_enter.setFont(font)
        self.key_kp_0 = QPushButton(self.keyboardGroup)
        self.key_kp_0.setObjectName(u"key_kp_0")
        self.key_kp_0.setGeometry(QRect(760, 230, 76, 36))
        self.key_kp_decimal = QPushButton(self.keyboardGroup)
        self.key_kp_decimal.setObjectName(u"key_kp_decimal")
        self.key_kp_decimal.setGeometry(QRect(840, 230, 36, 36))
        self.configGroup = QGroupBox(self.centralwidget)
        self.configGroup.setObjectName(u"configGroup")
        self.configGroup.setGeometry(QRect(8, 290, 926, 160))
        self.config_list = QListWidget(self.configGroup)
        self.config_list.setObjectName(u"config_list")
        self.config_list.setGeometry(QRect(10, 20, 200, 130))
        self.config_name = QLineEdit(self.configGroup)
        self.config_name.setObjectName(u"config_name")
        self.config_name.setGeometry(QRect(220, 20, 200, 30))
        self.load_config = QPushButton(self.configGroup)
        self.load_config.setObjectName(u"load_config")
        self.load_config.setGeometry(QRect(430, 20, 60, 30))
        self.save_config = QPushButton(self.configGroup)
        self.save_config.setObjectName(u"save_config")
        self.save_config.setGeometry(QRect(430, 60, 60, 30))
        self.delete_config = QPushButton(self.configGroup)
        self.delete_config.setObjectName(u"delete_config")
        self.delete_config.setGeometry(QRect(430, 100, 60, 30))
        self.start_button = QPushButton(self.centralwidget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(810, 460, 120, 40))
        font2 = QFont()
        font2.setPointSize(12)
        self.start_button.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"DNF\u6309\u952e\u8fde\u53d1\u5de5\u5177", None))
        self.keyboardGroup.setTitle(QCoreApplication.translate("MainWindow", u"\u6309\u952e\u8bbe\u7f6e - [ \u7ea2\u8272\u4e3a\u542f\u7528\u8fde\u53d1 \u84dd\u8272\u4e3a\u5173\u95ed\u8fde\u53d1 ]", None))
        self.key_esc.setText(QCoreApplication.translate("MainWindow", u"Esc", None))
        self.key_f1.setText(QCoreApplication.translate("MainWindow", u"F1", None))
        self.key_f2.setText(QCoreApplication.translate("MainWindow", u"F2", None))
        self.key_f3.setText(QCoreApplication.translate("MainWindow", u"F3", None))
        self.key_f4.setText(QCoreApplication.translate("MainWindow", u"F4", None))
        self.key_f5.setText(QCoreApplication.translate("MainWindow", u"F5", None))
        self.key_f6.setText(QCoreApplication.translate("MainWindow", u"F6", None))
        self.key_f7.setText(QCoreApplication.translate("MainWindow", u"F7", None))
        self.key_f8.setText(QCoreApplication.translate("MainWindow", u"F8", None))
        self.key_f9.setText(QCoreApplication.translate("MainWindow", u"F9", None))
        self.key_f10.setText(QCoreApplication.translate("MainWindow", u"F10", None))
        self.key_f11.setText(QCoreApplication.translate("MainWindow", u"F11", None))
        self.key_f12.setText(QCoreApplication.translate("MainWindow", u"F12", None))
        self.key_grave.setText(QCoreApplication.translate("MainWindow", u"`", None))
        self.key_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.key_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.key_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.key_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.key_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.key_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.key_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.key_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.key_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.key_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.key_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.key_equals.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.key_backspace.setText(QCoreApplication.translate("MainWindow", u"\u2190", None))
        self.key_tab.setText(QCoreApplication.translate("MainWindow", u"Tab", None))
        self.key_q.setText(QCoreApplication.translate("MainWindow", u"Q", None))
        self.key_w.setText(QCoreApplication.translate("MainWindow", u"W", None))
        self.key_e.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.key_r.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.key_t.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.key_y.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.key_u.setText(QCoreApplication.translate("MainWindow", u"U", None))
        self.key_i.setText(QCoreApplication.translate("MainWindow", u"I", None))
        self.key_o.setText(QCoreApplication.translate("MainWindow", u"O", None))
        self.key_p.setText(QCoreApplication.translate("MainWindow", u"P", None))
        self.key_leftbracket.setText(QCoreApplication.translate("MainWindow", u"[", None))
        self.key_rightbracket.setText(QCoreApplication.translate("MainWindow", u"]", None))
        self.key_backslash.setText(QCoreApplication.translate("MainWindow", u"\\", None))
        self.key_capslock.setText(QCoreApplication.translate("MainWindow", u"Caps", None))
        self.key_a.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.key_s.setText(QCoreApplication.translate("MainWindow", u"S", None))
        self.key_d.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.key_f.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.key_g.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.key_h.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.key_j.setText(QCoreApplication.translate("MainWindow", u"J", None))
        self.key_k.setText(QCoreApplication.translate("MainWindow", u"K", None))
        self.key_l.setText(QCoreApplication.translate("MainWindow", u"L", None))
        self.key_semicolon.setText(QCoreApplication.translate("MainWindow", u";", None))
        self.key_quote.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.key_enter.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.key_lshift.setText(QCoreApplication.translate("MainWindow", u"Shift", None))
        self.key_z.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.key_x.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.key_c.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.key_v.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.key_b.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.key_n.setText(QCoreApplication.translate("MainWindow", u"N", None))
        self.key_m.setText(QCoreApplication.translate("MainWindow", u"M", None))
        self.key_comma.setText(QCoreApplication.translate("MainWindow", u",", None))
        self.key_period.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.key_slash.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.key_rshift.setText(QCoreApplication.translate("MainWindow", u"Shift", None))
        self.key_lctrl.setText(QCoreApplication.translate("MainWindow", u"Ctrl", None))
        self.key_lwin.setText(QCoreApplication.translate("MainWindow", u"Win", None))
        self.key_lalt.setText(QCoreApplication.translate("MainWindow", u"Alt", None))
        self.key_space.setText(QCoreApplication.translate("MainWindow", u"Space", None))
        self.key_ralt.setText(QCoreApplication.translate("MainWindow", u"Alt", None))
        self.key_rwin.setText(QCoreApplication.translate("MainWindow", u"Win", None))
        self.key_menu.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.key_rctrl.setText(QCoreApplication.translate("MainWindow", u"Ctrl", None))
        self.key_printscreen.setText(QCoreApplication.translate("MainWindow", u"PrtSc", None))
        self.key_scrolllock.setText(QCoreApplication.translate("MainWindow", u"ScrLk", None))
        self.key_pause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.key_insert.setText(QCoreApplication.translate("MainWindow", u"Ins", None))
        self.key_home.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.key_pageup.setText(QCoreApplication.translate("MainWindow", u"PgUp", None))
        self.key_delete.setText(QCoreApplication.translate("MainWindow", u"Del", None))
        self.key_end.setText(QCoreApplication.translate("MainWindow", u"End", None))
        self.key_pagedown.setText(QCoreApplication.translate("MainWindow", u"PgDn", None))
        self.key_up.setText(QCoreApplication.translate("MainWindow", u"\u2191", None))
        self.key_left.setText(QCoreApplication.translate("MainWindow", u"\u2190", None))
        self.key_down.setText(QCoreApplication.translate("MainWindow", u"\u2193", None))
        self.key_right.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.key_numlock.setText(QCoreApplication.translate("MainWindow", u"Num", None))
        self.key_kp_divide.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.key_kp_multiply.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.key_kp_subtract.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.key_kp_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.key_kp_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.key_kp_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.key_kp_add.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.key_kp_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.key_kp_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.key_kp_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.key_kp_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.key_kp_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.key_kp_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.key_kp_enter.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.key_kp_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.key_kp_decimal.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.configGroup.setTitle(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e\u7ba1\u7406", None))
        self.config_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u914d\u7f6e\u540d\u79f0", None))
        self.load_config.setText(QCoreApplication.translate("MainWindow", u"\u8bfb\u53d6", None))
        self.save_config.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.delete_config.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.start_button.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
    # retranslateUi

